//! Shared test fixtures for tool tests (moved verbatim from `tools.rs`).
//!
//! Every per-tool `*_tests.rs` module uses these instead of cloning them
//! (rule 3: shared-first). Test-only: gated out of non-test builds.

use std::sync::Arc;

use crate::dispatcher::Dispatcher;
use crate::envelope::{DomainPayload, DomainRequest, IpcEnvelope, PROTOCOL_VERSION};
use ltmrs_compat::lemma::tool_args::{MemoryAddArgs, ToolArgs};
use ltmrs_domain::clock::FrozenClock;
use ltmrs_domain::command::Scope;
use ltmrs_domain::id::{
    ChannelId, DocumentRevision, EligibilityRevision, EntityId, EntityRevision, ExternalAlias,
    FrontendId, OperationId, StoreGeneration,
};
use ltmrs_domain::memory::{FragmentType, Instant, Memory, MemorySource};
use ltmrs_service::repository::CanonicalRepository;
use serde_json::Value;
use uuid::Uuid;

use super::execute_tool;

pub(crate) fn fe(n: u64) -> FrontendId {
    FrontendId::new(Uuid::from_u128(n as u128))
}

pub(crate) fn ch(n: u64) -> ChannelId {
    ChannelId::new(Uuid::from_u128(n as u128))
}

pub(crate) fn test_dispatcher() -> (Dispatcher, tempfile::TempDir) {
    let dir = tempfile::tempdir().unwrap();
    let clock: Arc<dyn ltmrs_domain::clock::Clock + Send + Sync> = Arc::new(FrozenClock::new(1000));
    let repo = Arc::new(
        CanonicalRepository::open_with_clock(dir.path().to_str().unwrap(), Arc::clone(&clock))
            .unwrap(),
    );
    repo.issue_namespace(fe(1), ch(1), 1000).unwrap();
    let registry = crate::registry::FrontendRegistry::new();
    (Dispatcher::new(repo, registry, clock), dir)
}

pub(crate) fn envelope(op: u64, body: DomainRequest) -> IpcEnvelope {
    IpcEnvelope {
        protocol_version: PROTOCOL_VERSION,
        store_generation: StoreGeneration::FIRST,
        frontend_id: fe(1),
        channel_id: ch(1),
        operation_id: OperationId::new(Uuid::from_u128(op as u128)),
        session: None,
        retry_epoch: 1,
        deadline_millis: None,
        scope: Scope::default(),
        body,
    }
}

pub(crate) fn tool_call(op: u64, tool: ToolArgs) -> IpcEnvelope {
    envelope(op, DomainRequest::ToolCall { tool })
}

pub(crate) fn run(disp: &Dispatcher, env: &IpcEnvelope, tool: &ToolArgs) -> DomainPayload {
    execute_tool(disp, env, tool).unwrap()
}

pub(crate) fn add_fragment(disp: &Dispatcher, op: u64, fragment: &str) -> String {
    let env = tool_call(
        op,
        ToolArgs::MemoryAdd(MemoryAddArgs {
            fragment: fragment.to_string(),
            ..Default::default()
        }),
    );
    let result = run(
        disp,
        &env,
        &ToolArgs::MemoryAdd(MemoryAddArgs {
            fragment: fragment.to_string(),
            ..Default::default()
        }),
    );
    if let DomainPayload::ToolResult {
        structured: Some(s),
        is_error: false,
        ..
    } = &result
    {
        s["id"].as_str().unwrap().to_string()
    } else {
        panic!("memory_add failed: {}", result_text(&result));
    }
}

pub(crate) fn result_text(p: &DomainPayload) -> String {
    match p {
        DomainPayload::ToolResult { text, .. } => text.clone(),
        _ => String::new(),
    }
}

pub(crate) fn result_structured(p: &DomainPayload) -> Option<Value> {
    match p {
        DomainPayload::ToolResult { structured, .. } => structured.clone(),
        _ => None,
    }
}

pub(crate) fn result_is_error(p: &DomainPayload) -> bool {
    match p {
        DomainPayload::ToolResult { is_error, .. } => *is_error,
        _ => false,
    }
}

pub(crate) fn text_contains(p: &DomainPayload, needle: &str) -> bool {
    result_text(p).contains(needle)
}

/// Path to the pinned upstream pure-functions oracle
/// (tests/compat/lemma_0_21_0/pure_functions.json): generated by running
/// the pinned upstream code on a set of inputs; ltmrs must reproduce the
/// upstream outputs byte-for-byte.
pub(crate) fn pure_oracle_path() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("../../tests/compat/lemma_0_21_0/pure_functions.json");
    p
}

/// Minimal memory fixture for oracle/stats tests.
pub(crate) fn make_memory(
    id: &str,
    project: Option<&str>,
    source: &str,
    confidence: f64,
    fragment: &str,
) -> Memory {
    Memory {
        id: EntityId::new(Uuid::new_v5(
            &Uuid::NAMESPACE_URL,
            format!("ltmrs:entity:{}", id).as_bytes(),
        )),
        external_alias: Some(ExternalAlias::new(id.to_string())),
        title: String::new(),
        fragment: fragment.to_string(),
        description: String::new(),
        fragment_type: FragmentType::Fact,
        project: project.map(|s| s.to_string()),
        source: MemorySource::parse(source).expect("valid source in oracle"),
        confidence,
        quality_score: None,
        lifecycle: ltmrs_domain::memory::MemoryLifecycle::Live,
        tags: Vec::new(),
        associated_with: Vec::new(),
        relations: Vec::new(),
        parent_id: None,
        child_ids: vec![],
        session_id: None,
        task_type: None,
        related_guides: Vec::new(),
        evidence: Vec::new(),
        access_count: 0,
        last_accessed_at: None,
        positive_feedback: 0,
        negative_feedback: 0,
        negative_hits: 0,
        refinement_count: 0,
        distill_candidate: false,
        entity_revision: EntityRevision::new(0),
        document_revision: DocumentRevision::new(0),
        eligibility_revision: EligibilityRevision::new(0),
        created_at: Instant::new(0),
        updated_at: Instant::new(0),
        raw_created: None,
        unknown_fields: Default::default(),
    }
}
