//! Pure-function differential tests vs upstream oracle (moved verbatim from `tools.rs`).

use super::test_support::*;
use super::text::{generate_description, normalize_project};
use ltmrs_domain::memory::Memory;
use serde_json::Value;

/// Filter memories by project scope (upstream `filterByProject` semantics).
/// No project → only global fragments. Project → that project's fragments
/// (case-insensitive) plus global fragments (project inheritance is deliberate).
#[cfg(test)]
fn filter_by_project<'a>(memories: &'a [Memory], current_project: Option<&str>) -> Vec<&'a Memory> {
    let project = current_project
        .map(|p| p.trim().to_lowercase())
        .filter(|p| !p.is_empty());
    memories
        .iter()
        .filter(|m| match (&project, m.project.as_deref()) {
            (None, mp) => mp.is_none(),
            (Some(p), Some(mp)) => mp.to_lowercase() == *p,
            (Some(_), None) => true,
        })
        .collect()
}

//]
// The oracle is generated by running the pinned upstream code on a set of
// inputs (see pure_oracle_path in test_support); ltmrs must reproduce
// the upstream outputs byte-for-byte.

/// The frozen clock reference baked into the oracle (2026-09-23T12:00:00Z).
const ORACLE_NOW_MILLIS: u64 = 1_790_164_800_000;

#[test]
fn calculate_quality_score_matches_upstream() {
    use ltmrs_compat::lemma::reference::{QualityCounters, calculate_quality_score};
    let raw = std::fs::read_to_string(pure_oracle_path()).expect("pure_functions.json must exist");
    let oracle: Value = serde_json::from_str(&raw).expect("valid JSON oracle");
    for (i, case) in oracle["calculateQualityScore"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let input = &case["input"];
        let counters = QualityCounters {
            confidence: input["confidence"].as_f64().unwrap(),
            positive_feedback: input["positive_feedback"].as_u64().unwrap(),
            negative_feedback: input["negative_feedback"].as_u64().unwrap(),
            accessed: input["accessed"].as_u64().unwrap(),
            refinement_count: input["refinement_count"].as_u64().unwrap(),
            last_accessed_millis: input["lastAccessedMillis"].as_u64(),
            negative_hits: input["negativeHits"].as_u64().unwrap(),
        };
        let actual = calculate_quality_score(&counters, ORACLE_NOW_MILLIS);
        let expected = case["output"].as_f64().unwrap();
        assert!(
            (actual - expected).abs() < 1e-9,
            "calculate_quality_score mismatch on case {i}: {actual} vs {expected}"
        );
    }
}

#[test]
fn injection_score_matches_upstream() {
    use ltmrs_compat::lemma::reference::injection_score;
    let raw = std::fs::read_to_string(pure_oracle_path()).expect("pure_functions.json must exist");
    let oracle: Value = serde_json::from_str(&raw).expect("valid JSON oracle");
    for (i, case) in oracle["injectionScore"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let input = &case["input"];
        let actual = injection_score(
            input["confidence"].as_f64().unwrap(),
            input["createdMillis"].as_u64().unwrap(),
            ORACLE_NOW_MILLIS,
        );
        let expected = case["output"].as_f64().unwrap();
        assert!(
            (actual - expected).abs() < 1e-9,
            "injection_score mismatch on case {i}: {actual} vs {expected}"
        );
    }
}

#[test]
fn generate_description_matches_upstream() {
    let raw = std::fs::read_to_string(pure_oracle_path()).expect("pure_functions.json must exist");
    let oracle: Value = serde_json::from_str(&raw).expect("valid JSON oracle");
    for (i, case) in oracle["generateDescription"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let input = case["input"].as_str().unwrap();
        let expected = case["output"].as_str().unwrap();
        let actual = generate_description(input);
        assert_eq!(
            actual, expected,
            "generate_description mismatch on case {i}: input={input:?}"
        );
    }
}

#[test]
fn normalize_project_matches_upstream() {
    let raw = std::fs::read_to_string(pure_oracle_path()).expect("pure_functions.json must exist");
    let oracle: Value = serde_json::from_str(&raw).expect("valid JSON oracle");
    for (i, case) in oracle["resolveProjectScope"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let Some(input) = case["input"].as_str() else {
            continue;
        };
        let expected: Option<String> = case["output"].as_str().map(|s| s.to_string());
        let actual = normalize_project(input);
        assert_eq!(
            actual, expected,
            "normalize_project mismatch on case {i}: input={input:?}"
        );
    }
}

#[test]
fn filter_by_project_matches_upstream() {
    let raw = std::fs::read_to_string(pure_oracle_path()).expect("pure_functions.json must exist");
    let oracle: Value = serde_json::from_str(&raw).expect("valid JSON oracle");
    for (i, case) in oracle["filterByProject"]
        .as_array()
        .unwrap()
        .iter()
        .enumerate()
    {
        let memories: Vec<Memory> = case["input"]["fragments"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| {
                make_memory(
                    f["id"].as_str().unwrap(),
                    f["project"].as_str(),
                    "ai",
                    0.5,
                    "",
                )
            })
            .collect();

        let current_project = case["input"]["currentProject"].as_str();
        let actual: Vec<String> = filter_by_project(&memories, current_project)
            .iter()
            .map(|m| m.external_alias.as_ref().unwrap().as_str().to_string())
            .collect();
        let expected: Vec<String> = case["output"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_string())
            .collect();
        assert_eq!(actual, expected, "filter_by_project mismatch on case {i}");
    }
}
